CODES = {}
CODES['UNEXPECTED'] = 999
CODES['USER_ERROR'] = 998
CODES['SINTAX_ERROR'] = 997
CODES['LEXICAL_ERROR'] = 996
CODES['EOI_ERROR'] = 995
CODES['SYMBOL_NAME_NOT_FOUND'] = 994
CODES['SYMBOL_TYPE_NOT_FOUND'] = 993
CODES['TYPE_ERROR'] = 992
CODES['ALREADY_DECLARED_ERROR'] = 991
CODES['SUBPROPERTY_NOT_FOUND'] = 990
CODES['INDEX_OUT_OF_RANGE'] = 989
CODES['NONE_VALUE_RETURNED'] = 988
CODES['FORMULA_NOT_FOUND'] = 987
CODES['QUANTITY_IS_NOT_VALID'] = 986
CODES['OPERATION_DIMENSIONALITY_ERROR'] = 985
CODES['OPERATION_UNDEFINED_UNIT_ERROR'] = 984
CODES['OPERATION_ERROR'] = 983


class UserDefinedError:
    def __init__(self, msg):
        self.msg = msg